// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/12 15:27:21
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/plugins/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/composables/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/utils/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-1/routine-timetable/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;